#!/bin/bash

# Setup script for Registration Portal Configuration
# This script generates the env-config.js file from environment variables
# Usage: ./setup-registration-portal.sh
# or with env vars: VITE_SUPABASE_URL=... VITE_SUPABASE_ANON_KEY=... ./setup-registration-portal.sh

set -e

# Directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/env-config.js"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Registration Portal Configuration Setup${NC}"
echo "=========================================="

# Check if environment variables are set
if [ -z "$VITE_SUPABASE_URL" ] || [ -z "$VITE_SUPABASE_ANON_KEY" ]; then
    echo -e "${RED}❌ Error: Missing environment variables${NC}"
    echo ""
    echo "Please set the following environment variables before running this script:"
    echo "  - VITE_SUPABASE_URL"
    echo "  - VITE_SUPABASE_ANON_KEY"
    echo ""
    echo "You can set them in your shell:"
    echo "  export VITE_SUPABASE_URL=https://your-project.supabase.co"
    echo "  export VITE_SUPABASE_ANON_KEY=your-anon-key"
    echo ""
    echo "Or use a .env file in the project root and source it:"
    echo "  source ../.env && ./setup-registration-portal.sh"
    echo ""
    exit 1
fi

# Create the env-config.js file
cat > "$CONFIG_FILE" << EOF
/**
 * Environment Configuration for Registration Portal
 * 
 * Auto-generated by setup-registration-portal.sh script
 * Generated: $(date)
 * 
 * This file contains the Supabase credentials for the registration portal.
 * It ensures the portal uses the same Supabase project as the main app.
 */

window.REGISTRATION_CONFIG = {
  SUPABASE_URL: '$VITE_SUPABASE_URL',
  SUPABASE_ANON_KEY: '$VITE_SUPABASE_ANON_KEY',
  DEBUG: false
};

console.log('[Registration Config] ✅ Supabase configuration loaded');
EOF

echo -e "${GREEN}✅ Configuration file generated: $CONFIG_FILE${NC}"
echo ""
echo "Configuration Details:"
echo "  URL: $VITE_SUPABASE_URL"
echo "  Key: ${VITE_SUPABASE_ANON_KEY:0:20}..."
echo ""
echo "Next steps:"
echo "1. Open registration-portal/index.html in your browser"
echo "2. Register a user through the portal"
echo "3. Check your Supabase dashboard to verify the registration was saved"
echo ""
