// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Log environment status for debugging
console.log('[Supabase Client] Checking environment variables...');
console.log('[Supabase Client] VITE_SUPABASE_URL:', supabaseUrl ? 'SET' : 'MISSING');
console.log('[Supabase Client] VITE_SUPABASE_ANON_KEY:', supabaseKey ? 'SET' : 'MISSING');

if (!supabaseUrl || !supabaseKey) {
  const missing = [];
  if (!supabaseUrl) missing.push('VITE_SUPABASE_URL');
  if (!supabaseKey) missing.push('VITE_SUPABASE_ANON_KEY');
  
  const errorMsg = `[CRITICAL] Missing environment variables: ${missing.join(', ')}\n\nPlease set these in your .env.local file or Vercel environment variables:\n1. VITE_SUPABASE_URL - Your Supabase project URL\n2. VITE_SUPABASE_ANON_KEY - Your Supabase anonymous key\n\nGet these from: https://supabase.com/dashboard -> Settings -> API`;
  
  console.error(errorMsg);
  
  // Display error on page
  if (typeof window !== 'undefined') {
    document.body.innerHTML = `
      <div style="padding: 40px; font-family: monospace; background: #fee; color: #c00; border: 2px solid #c00; margin: 20px;">
        <h1>❌ Configuration Error</h1>
        <pre style="background: #fff; padding: 20px; border-radius: 4px; overflow-x: auto;">${errorMsg}</pre>
        <p style="margin-top: 20px; font-size: 14px;">
          For production (Vercel), add these in Project Settings → Environment Variables<br/>
          For local development, create a <code>.env.local</code> file in the project root
        </p>
      </div>
    `;
  }
  
  throw new Error(errorMsg);
}

const getSafeStorage = (): Storage => {
  try {
    const testKey = "__storage_test__";
    window.localStorage.setItem(testKey, testKey);
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch (e) {
    console.warn("Storage access denied, falling back to in-memory storage:", e);
    const store: Record<string, string> = {};
    return {
      getItem: (key: string) => store[key] || null,
      setItem: (key: string, value: string) => { store[key] = value; },
      removeItem: (key: string) => { delete store[key]; },
      clear: () => { for (const k in store) delete store[k]; },
      key: (index: number) => Object.keys(store)[index] || null,
      get length() { return Object.keys(store).length; }
    } as Storage;
  }
};

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log('[Supabase Client] Successfully initialized');